SELECT
	 i.< COLUMN >
	,c.dupeCount

FROM
	< TABLE > AS i

INNER JOIN (

		SELECT		< SAME COLUMN AS ABOVE >, COUNT(*) AS dupeCount
		FROM		< SAME TABLE AS ABOVE >
		GROUP BY	< SAME COLUMN AS ABOVE >
		HAVING COUNT(*) > 1

	) c ON i.< SAME COLUMN AS ABOVE > = c.< SAME COLUMN AS ABOVE >